###
GET http://localhost:4004/catalog/
Authorization: Basic alice:

###
GET http://localhost:4004/catalog/Books
Authorization: Basic alice:

###
POST http://localhost:4004/catalog/Books
Authorization: Basic alice:
Content-Type: application/json

{
    "title": "Per Anhalter durch die Galaxis",
    "stock": 42
}

###
GET http://localhost:4004/admin/

###
GET http://localhost:4004/admin/Books

###
GET http://localhost:4004/v2/catalog/
Authorization: Basic alice:

###
GET http://localhost:4004/v2/catalog/Books
Authorization: Basic alice: